#!/bin/sh
#
# chkconfig: - 91 35
# description: Starts and stops the Rollout server
#              #
# pidfile: /var/run/rolloutd.pid


RUN_ON_STARTUP=0
BASEDIR="/usr/local/rollout"
ALLOW="127.0.0.0/24"
LISTEN_ADDRESS="127.0.0.1"
LISTEN_PORT=80
LOGFILE="/var/log/rolloutd.log"
ROLLOUTD="/usr/local/sbin/rolloutd"
PIDFILE="/var/run/rolloutd.pid"
LISTEN_SSL=""
USER=nobody
GROUP=daemon

[ -f /etc/default/rollout ] && . /etc/default/rollout

check_status() {
  [ -f ${PIDFILE} ] || return 0
  PID=`cat ${PIDFILE}`
  [ -z ${PIDFILE} ] && return 0
  kill -0 ${PID} 2>/dev/null && return ${PID}
  return 0
}

case "$1" in
  start)
    [ -z ${RUN_ON_STARTUP} -o ${RUN_ON_STARTUP} != 1 ] && exit 0
    [ -d ${BASEDIR} ] || mkdir -p "${BASEDIR}"
    echo "Starting Rollout"
    cd `dirname ${ROLLOUTD}`
    ${ROLLOUTD} \
      --daemon \
      --pidfile "${PIDFILE}" \
      --base "${BASEDIR}" \
      --allow "${ALLOW}" \
      --listen "${LISTEN_ADDRESS}:${LISTEN_PORT}" \
      ${LISTEN_SSL} \
      --user "${USER}" \
      --group "${GROUP}" \
      --logfile "${LOGFILE}" \
      >> /var/log/rolloutd.log 2>&1
    ;;
  stop)
    check_status && exit 0
    PID=`cat ${PIDFILE}`
    echo "Stopping Rollout (process $PID)"
    kill $PID
    rm -f /var/run/rolloutd.pid
    ;;
  restart)
    $0 stop
    $0 start
    exit $?
    ;;
  status)
    check_status && echo "Rollout is not running" && exit 1
    PID=`cat ${PIDFILE}`
    echo "Rollout is running as PID $PID"
    exit 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

