#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
=head1 NAME

003-modifiers

=head1 DESCRIPTION

This step doesn't do any configuration, it's used to download the modification code that will be
used by later steps..

B<This is a required step and will always be run, no matter what C<skip_steps> configurations or
C<-o> command line options are specified.>

=head1 EXAMPLE

There is no configuration for this step.

=head1 COPYRIGHT

Copyright 2010 David Parrish

=cut

sub config_file {
  my $p = named_params @_, [ -file => undef, -sections => undef, -cmd => undef, -type => "ini",
                             -uid => undef, -owner => undef, -gid => undef, -group => undef,
                             -mode => undef, -separator => "="];
  throw ConfigException "No file specified" unless $p->{-file};
  throw ConfigException "No sections specified" unless $p->{-sections};

  my @config;
  while (my($name, $config) = each %{$p->{-sections}}) {
    push @config, "[$name]" if $name;
    for (my $i = 0; $i < @$config; $i += 2) {
      push @config, "$config->[$i]$p->{-separator}$config->[$i + 1]";
    }
    push @config, "";
  }

  delete $p->{-sections};
  delete $p->{-separator};
  $p->{-text} = join("", map { "$_\n" } @config);
  text_install(%$p);
}
