#!/usr/bin/perl -w
# Example: 
# pre_pkg_dir_check => [
#	[ '/tmp/foobar', 0750 ],
#	[ -dir => '/tmp/foobar2', -mode => 04755, -uid => 1000 ],
# ],

dir_check(@$_) foreach flatten_list(c("pre_pkg_dir_check"));

