#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
# Example:
# pre_pkg_dir_check => [
#  [ '/tmp/foobar', 0750 ],
#  [ -dir => '/tmp/foobar2', -mode => 04755, -uid => 1000 ],
# ],

validate_step_config {
  dir_check => {
    type => "list",
    items => {
      type => [ "list", "hash_list" ],
      items => { type => "string" }
    },
  },
};

dir_check(@$_) foreach flatten_list(c("$hostname/pre_pkg_dir_check"));

