#!/usr/bin/perl -w
# Add entries to /etc/sysctl.conf
# vim:tw=100 sw=2 expandtab ft=perl

validate_config {
  sysctl => {
    type => "hash",
    key => {
      help => "Sysctl name",
      type => "string",
      regex => qr/^[\w_\-]+.[\w_\-.]+$/,
    },
    value => {
      help => "Sysctl value",
      type => "string",
    },
  },
};

my $changed = 0;
my %sysctl = flatten_hash(c("$hostname/sysctl"));
while (my($item, $value) = each(%sysctl)) {
  my $text = i_os("freebsd") ? "$item=$value" : "$item = $value";
  file_append(-file => "/etc/sysctl.conf", -add => $text, -match => qr/^#?\s*$item/,
              -uid => 0, -gid => 0) and $changed++;
}

if ($changed) {
  if (i_os("linux")) {
    command("sysctl", "-p", "/etc/sysctl.conf");
  } elsif (i_os("freebsd")) {
    command("/etc/rc.d/sysctl", "restart");
  } else {
    throw ConfigException "Don't know how to reload sysctl entries on ". i_os();
  }
}
