#!/usr/bin/perl -w
# CVS checkout
# vim:tw=100 sw=2 expandtab ft=perl

# Example:
# cvspass => {
#   # This gets installed to /root/.cvspass
#   ':pserver:rollout@cvs.domain:2401/home/cvs' => 'Ahohlasd=',
# },
#
# cvs => {
#   '/tmp/checkout_dir' => {
#     module => 'cvs_module',
#     rev => 'HEAD',
#     repository => ':pserver:rollout@cvs.domain:2401/home/cvs',
#     cmd => 'ls -l /tmp/checkout_dir',
#   },
# },

validate_config {
  cvapass => {
    type => "hash",
    key => {
      help => "CVSROOT",
      type => "string",
    },
    value => {
      help => "Encoded password",
      type => "string",
    },
  },
  cvs => {
    type => "hash",
    key => {
      type => "path",
    },
    value => {
      type => "options",
      options => {
        module => { type => "string", help => "CVS module name" },
        rev => { type => "string", help => "Revision to check out" },
        repository => { type => "string", help => "CVSROOT" },
        cmd => { type => "string", help => "Post checkout command to run (in checked out dir)" },
      },
    },
  },
  cvsoptions => {
    help => "Options for each cvs command",
    type => "options",
    options => {
      cvs => { type => "string" },
      update => { type => "string" },
      checkout => { type => "string" },
      diff => { type => "string" },
    },
    fail_on_unknown => 0,
  },
};

return unless i_has('cvs');

my %cvspass = flatten_hash(c("$hostname/cvspass"));
while (my($user, $pass) = each %cvspass) {
  file_append(-file => "/root/.cvspass", -add => "/1 $user $pass", -match => qr/ $user /,
              -uid => 0, -gid => 0, -mode => 0600, -create => 1);
}

my %o = flatten_hash(c("$hostname/cvsoptions"));
$o{cvs} ||= "-z3 -q";
$o{update} ||= "-d -P";
$o{checkout} ||= "-P";
$o{diff} ||= "-u -b -B";

file_append(-file => "/root/.cvsrc", -add => "$_ $o{$_}", -match => qr/^$_/, -create => 1)
  foreach keys %o;

my %cvs = flatten_hash(c("$hostname/cvs"));
package_check("cvs") if keys %cvs;
while (my($dir, $x) = each(%cvs)) {
  w "No module specified for $dir" or next unless $x->{module};

  cvs_checkout(-dest => $dir, -module => $x->{module}, -rev => $x->{rev}, -repo => $x->{repository},
               -cmd => $x->{post_cmd});
}
