#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
=head1 NAME

240-dir_check

=head1 DESCRIPTION

Creates directories with set permissions.

=head1 EXAMPLE

  class Sample => {
    dir_check => [
      [ -dir => '/tmp/dir1', -mode => 0777, -uid => 'root', -gid => 'daemon' ],
      [ '/tmp/dir2', 0777, 'root', 'daemon' ],
    ],
  };

=head1 OPTIONS

=over

=item dir_check/path

Create the given directory. Options can be specified either as a set of -
prefixed options, or a short ordered list.

=back

=head1 COPYRIGHT

RolloutNG is based heavily on Rollout (https://github.com/dparrish/rollout) by David Parrish, Copyright 2010.   RolloutNG is Copyright by Chris Donovan 2014.

=cut

validate_config {
  dir_check => {
    type => "list",
    items => {
      type => [ "list", "hash_list" ],
      items => { type => "string" }
    },
  },
};

dir_check(@$_) foreach flatten_list(c("$hostname/dir_check"));
