#!/usr/bin/perl -w
# Install files and symlink
# vim:tw=100 sw=2 expandtab ft=perl
#
# Example:
#
# file_install => {
#   '/tmp/dest_file' => {
#     source => 'rollout:/conf/source_file',
#     command => 'ls -l /tmp/dest_file',
#     mode => 0640,
#     uid => 1000,
#     gid => 1000,
#   },
#   '/tmp/dest_file' => {
#     text => 'This is some text\n',
#   },
# },
# symlink_check => {
#   '/tmp/dest' => '/tmp/source',
# },

my %done_files;
my %files = flatten_hash(c("$hostname/file_install"));
while (my($dest, $f) = each(%files)) {
  next if $done_files{$dest}++;
  next if i_immutable_file($dest);
  next unless i_should($dest);
  if ($f->{source}) {
    file_install(-file => $dest, -src => $f->{source}, -cmd => $f->{command} || undef,
                 -mode => $f->{mode}, -uid => $f->{uid}, -gid => $f->{gid});
  } elsif ($f->{text}) {
    if ($f->{text} =~ /^\n?(\s+)/m) {
      my $strip = $1;
      v "Stripping \"$strip\" from the start of text for file: $dest";
      my @text = split(/\n/, $f->{text});
      $f->{text} = "";
      foreach (@text) { s/^$strip//; $f->{text} .= "$_\n"; };
    }
    text_install(-file => $dest, -text => $f->{text}, -cmd => $f->{command} || undef,
                 -mode => $f->{mode}, -uid => $f->{uid}, -gid => $f->{gid});
  }
}

my %symlinks = flatten_hash(c("$hostname/symlink_check"));
while (my($dest, $src) = each %symlinks)
{
  if (ref $src eq 'ARRAY')
  {
    my @list = uniq(@$src);
    validate("You have multiple symlink_check definitions for $dest, you must only have one.",
             @list == 1);
    $src = $list[0];
  }
  symlink_check($src, $dest);
}
