#!/usr/bin/perl -w

my %dir_install = flatten_hash(c("dir_install"));
while (my($dest, $src) = each(%dir_install))
{
	next unless i_should($dest);
	$src = { -src => $src, -dest => $dest } if ref $src ne 'HASH';
	$src = { map { (/^-/ ? $_ : "-$_") => $src->{$_} } keys %$src };
	$src->{-src} = $src->{-source};
	$src->{-dest} = $dest;
	delete $src->{-source};
	dir_install(%$src);
}
