#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
# Example:
#
# dir_install => {
#   '/tmp/test' => {
#     source => 'rollout:/files/test',
#     dir_mode => 0755,
#     mode => 0644,
#     owner => 'root',
#     group => 'daemon',
#     command => "find /tmp/test -ls",
#   },
# },

validate_config {
  dir_install => {
    type => "hash",
    key => {
      help => "Local path to install to",
      type => "path",
    },
    value => {
      type => "options",
      options => {
        command => { type => "string" },
        dir_mode => { type => "int", range => [0, 07777], help => "Mode for directories" },
        gid => { type => "int", range => [0, 65535] },
        group => { type => "string", regex => qr/^[a-z0-9_\-.]+$/ },
        mode => { type => "int", range => [0, 07777], help => "Mode for files" },
        owner => { type => "string", regex => qr/^[a-z0-9_\-.]+$/ },
        source => { type => "string" },
        uid => { type => "int", range => [0, 65535] },
      },
    },
  },
};

my %dir_install = flatten_hash(c("$hostname/dir_install"));
while (my($dest, $src) = each(%dir_install)) {
  next unless i_should($dest);
  $src = { -src => $src } if ref $src ne 'HASH';
  $src = { map { (/^-/ ? $_ : "-$_") => $src->{$_} } keys %$src };
  $src->{-dest} |= $dest;
  $src->{-src} ||= $src->{-source} if $src->{-source};
  $src->{-cmd} ||= $src->{-command} if $src->{-command};
  dir_install(%$src);
}
