#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
=head1 NAME

270-port_check

=head1 DESCRIPTION

Add a list of port <-> service name mappings to /etc/services.

=head1 EXAMPLE

  $m{Sample} = {
    port_check => [
      svc1 => 1000,
      svc2 => '1000:tcp',  # TCP is default if not specified
      svc3 => {
        comment => 'Generic UDP Service',
        port => '1001:udp',
      },
    ],
  };

=head1 COPYRIGHT

Copyright 2010 David Parrish

=cut


validate_config {
  port_check => {
    help => "List of ports to add to /etc/services",
    type => "hash_list",
    key => {
      help => "Service name",
      type => "string",
    },
    value => {
      help => "Port number",
      type => [ "string", "options" ],
      regex => qr/^\d+(\/(?:tcp|udp))?$/,
      options => {
        comment => { type => "string" },
        port => { type => "string", regex => qr/^\d+(\/(?:tcp|udp))?$/ },
      },
    },
  },
};

my @ports = flatten_list(c("$hostname/port_check"));
for (my $i = 0; $i < @ports; $i += 2) {
  my($name, $port, $comment) = ($ports[$i], $ports[$i + 1], undef);
  if (ref $port eq 'HASH') {
    $comment = $port->{comment};
    $port = $port->{port};
  }
  next unless $name && $port;
  next unless i_should($name) && i_should($port);

  $comment ||= "";
  $port = "$port/tcp" unless $port =~ /\//;

  file_append(-file => "/etc/services",
              -add => sprintf("%-15s %-20s # %s", $name, $port, $comment),
              -match => qr/^$name\s+$port/);

}
