#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
=head1 NAME

451-rubygems

=head1 DESCRIPTION

Install Ruby Gems

=head1 EXAMPLE

  class Sample => {
    gems => [ "rails" ],
  };

=head1 COPYRIGHT

Copyright 2013 David Parrish

=cut

validate_config {
  gems => {
    type => "list",
    help => "List of ruby gems to install",
    items => { type => "string" },
  },
};

if (i_has("gems")) {
  package_check("rubygems");
  command("gem", "install", "-V", $_) foreach flatten_list(c("$hostname/gems"));
}
