#!/usr/bin/perl -w
# Modify files according to the file_modify section

foreach (i_isa_fetchall("file_modify"))
{
  for (my $i = 0; $i < @$_; $i += 2)
  {
    my($filename, $changes) = ($_->[$i], $_->[$i+1]);
    next unless ref $changes eq 'ARRAY';
    file_modify($filename, undef, @$changes);
  }
}
