#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
=head1 NAME

800-file_append

=head1 DESCRIPTION

Modify files according to the file_append section

=head1 EXAMPLE

  class Sample => {
    file_append => [
      [
        "/etc/aliases",                # The file to change
        "root: root\@yourdomain.com",  # The line to add
        qr/^root/,                     # Replace any lines matching this regex
        "newaliases",                  # Run this if the file is changed
        1,                             # Create the file if it doesn't already exist
      ],
    ],
  };

=head1 COPYRIGHT

Copyright 2010 David Parrish

=cut

validate_config {
  file_append => {
    type => "list",
    items => {
      type => [ "list", "options" ],
      # TODO(dparrish): Do some proper validation of each entry here
      items => { type => [ "string", "regex" ] },
    },
  },
};

file_append(@$_) foreach flatten_list(c("$hostname/file_append"));
