#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
=head1 NAME

802-file_modify

=head1 DESCRIPTION

Modify files according to the file_modify section

=head1 EXAMPLE

  class Sample => {
    file_modify => [
      '/etc/updatedb.conf' => [
        # Run this regex replacement across every line in the file
        's/^DAILY_UPDATE=no/DAILY_UPDATE=yes/',
      ],
    ],
  };

=head1 COPYRIGHT

RolloutNG is based heavily on Rollout (https://github.com/dparrish/rollout) by David Parrish, Copyright 2010.   RolloutNG is Copyright by Chris Donovan 2014.

=cut

validate_config {
  file_modify => {
    type => "hash_list",
    key => {
      type => "path",
    },
    value => {
      help => "List of regex style replaces to run on the file",
      type => "list",
      items => { type => "string" },
    },
  },
};

my @list = flatten_list(c("$hostname/file_modify"));
file_modify(-file => shift @list, -modify => shift @list) while @list;
