#!/usr/bin/perl -w
# Modify files according to the file_modify section
# vim:tw=100 sw=2 expandtab ft=perl
#
# Example:
#
# file_modify => [
#   '/etc/updatedb.conf' => [
#     's/^DAILY_UPDATE=no/DAILY_UPDATE=yes/',  # Run this regex across every line in the file
#   ],
# ],

my @list = flatten_list(c("$hostname/file_modify"));
file_modify(-file => shift @list, -modify => shift @list) while @list;
