#!/usr/bin/perl -w

foreach (i_isa_fetchall("crontab_include"))
{
  while(my($line, $match) = each(%$_))
  {
    file_append("/etc/crontab", $line, $match);
  }
}

foreach (i_isa_fetchall("crontab"))
{
  while(my($name, $lines) = each(%$_))
  {
    text_install("/etc/cron.d/$name", join("\n", @$lines). "\n");
  }
  
}
