#!/usr/bin/perl -w
#
# Example:
#
# crontab => {
#   test_file => [
#     '* * * * * root ps fax >/dev/null',
#   ],
# },

my %crontab = flatten_hash(c("crontab"));
map { text_install("/etc/cron.d/$_", join("\n", @{$crontab{$_}}). "\n") } keys %crontab;

my %crontab_include = flatten_hash(c("crontab_include"));
map { file_append("/etc/crontab", $_, $crontab_include{$_}) } keys %crontab_include;

