#!/usr/bin/perl -w
# vim:tw=100 sw=2 expandtab ft=perl
=head1 NAME

970-motd

=head1 DESCRIPTION

Update the Message Of The Day. You can specify a message in each config fragment, and they will be
appended together.

The first part of the motd is always:

 Updated by rollout at Tue Aug 31 12:08:01 2010 from 172.16.140.1

=head1 EXAMPLE

  class Sample => {
    motd => "Have a nice day.",
  };

=head1 OPTIONS

=over

=item motd

Append this string to the message of the day.

=back

=head1 COPYRIGHT

Copyright 2010 David Parrish

=cut

validate_config {
  motd => {
    help => "Message of the day",
    type => "string",
  },
};

my $text = `uname -a`;


my($host, $srcport, $sshport) = split(/\s/, $ENV{SSH_CLIENT}) if $ENV{SSH_CLIENT};
$host ||= POSIX::ttyname(1);
if ($host =~ /(?:::ffff:)?(\d+\.\d+\.\d+\.\d+)\s+(\d+)\s+\d+/) {
  $host = $1 || "127.0.0.1";
  $sshport = $2 || 0;
  my $ip_type;
  my $ip_type = ($host =~ /:/) ? 'AF_INET' : 'AF_INET6';
  my $x = gethostbyaddr(inet_aton($host), $ip_type);
}

$text .= "\nUpdated by rollout at ". localtime(time). " from $host";
$text .= ":$sshport" if $sshport;
$text .= "\n\n".  join("\n", flatten_list(c("$hostname/motd")));

text_install("/etc/motd", $text);
