#!/usr/bin/perl -w
# Run any queued commands or queued code blocks
# vim:tw=100 sw=2 expandtab ft=perl
#
# Example:
#
# queue_command => [
#   'ls -l /tmp',
# ],
# queue_code => sub { l 'Hello world' },

map { command(ref $_ eq 'ARRAY' ? @$_ : $_) } flatten_list(c("queue_command"));
map { $_->() } flatten_list(c("queue_code"));
